name: kaostomat
favicon: null
layout_spectrum: 0.98887
typography_spectrum: 0.40325
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
